api/res/config.toml
api/res/openapi.yml
api/src/apps.rs
api/src/infrastructure/docker.rs
api/src/infrastructure/dummy_infrastructure.rs
api/src/infrastructure/infrastructure.rs
api/src/main.rs
api/src/models/app_name.rs
api/src/models/logs_chunks.rs
api/src/models/mod.rs
api/src/services/apps_service.rs
frontend/package-lock.json
frontend/package.json
frontend/src/App.vue
frontend/src/Dialog.vue
frontend/src/LogsDialog.vue
frontend/src/ReviewAppCard.vue

This PR adds following features:
- Add an REST resource to retrieve the log messages of a service of an review app with pagination.
- Utilize this resource to display the log messages in the frontend.

Frontend: Retrieve and Display Logs of Services

---

api/Cargo.lock
api/Cargo.toml
api/README.md
api/src/config/app_selector.rs
api/src/config/companion.rs
api/src/config/config.rs
api/src/config/secret.rs
api/src/models/image.rs
api/src/models/service_config.rs

Secrets can be configured with an optional path. Fixes #27.

Extend Secret Configuration with Path

---

api/src/apps/apps.rs
api/src/apps/deployment_unit.rs

PREvant did not include the service that are running when it applied templating for application companions. This commit fixes this issue by including it into the DeploymentUnit.

Fix: Apply Templating With Running Services

---

frontend/src/App.vue
frontend/src/Spinner.vue
frontend/src/store/index.js

The frontend handles backend error and displays them.

Improved Error Handling

---

api/Cargo.lock
api/Cargo.toml
api/src/apps/apps.rs
api/src/apps/host_meta_cache.rs
api/src/apps/mod.rs
api/src/apps/routes.rs
api/src/main.rs
api/src/models/mod.rs
api/src/models/service.rs
api/src/models/web_host_meta.rs
api/src/tickets.rs
api/src/webhooks.rs

The web host meta resolving is be moved to a background thread (every 5 seconds currently)
Fixes #46

Separate Caching of Web-Host from HTTP Responder

---

api/src/apps/host_meta_cache.rs

fix that network might take a little at startup: sleep at beginning of loop and try for the first minute after startup to fetch meta data even if container is older than 5 min.

fix of network delay after prevant startup causing meta data problems

---

api/src/apps/host_meta_cache.rs
api/src/apps/mod.rs
api/src/apps/routes.rs
api/src/main.rs
api/src/tickets.rs

Does not seem to improve memory usage by itself. But here's the change anyway 🙃

Use the global runtime in tickets.rs

---

api/src/apps/hooks.rs

There is a bug in the hooks:
Currently either all env variables in a deploymentHook are written if the config does not contain a env section yet or only already existing keys are overwritten. This bugfix also adds new env variables if already other env variables exist in the config.

Fix of hooks: enable adding of new env variables if env already exists

---

api/src/models/image.rs

Since images could have None values for registry, image_user and image_tag, a PartialEq overload is needed for comparison.

add PartialEq for images because of possible None comparison

---

frontend/src/Dialog.vue

See https://getbootstrap.com/docs/4.0/components/modal/#options

Make modal dialogs escapable

---

api/res/openapi.yml

Fix mismatch between openAPI spec and actual API

---

api/src/apps/host_meta_cache.rs
api/src/apps/routes.rs
api/src/infrastructure/dummy_infrastructure.rs

Added testcases to ensure a successful URL generation after adding the code to deal with x-forwarded-header values.
Fixes #109

Test Cases for URL Generation

---

api/src/infrastructure/kubernetes/deployment_unit.rs
api/src/infrastructure/kubernetes/infrastructure.rs

If the application is bootstrapped by a bootstap container and then companions have been converted into instances, and then the instances should be updated with a subsequent HTTP request, the application ends up with a second version of the instance. This circumstance is not intended and this commit makes sure that subsequent HTTP requests update existing deployments while taking the bootstrapping into account.
Related to #146

Fix Duplicate Deployments in Bootstrapped Apps

---

README.md

Development section needed more structure and some punctuation marks were missing. Grammatical mistakes are intended to be  corrected.

Development section Update README.md

---

README.md

The introduction for PREvant was incomplete and had mistakes. Thus, I have made changes to add more meaning to this section

PREvant introduction Update README.md

---

api/README.md

Grammatical errors correction and fixed sentence structure

Services and Secrets Section Update README.md

---

api/README.md

Minor sentence structure correction for better readability.

Issue Tracking Options Update README.md

---

api/README.md

In this section, I've tried to make changes for reader's better comprehension.

Configuration and Customization section Update README.md

---

api/README.md

Elaborated a little in this section

Container Options Section Update README.md

---

api/README.md

Added structure to the sentence fixing grammar.

Configure With Environment Variables Section Update README.md

---

api/Cargo.lock
api/Cargo.toml
api/README.md
api/src/config/mod.rs
api/src/models/image.rs
api/src/registry.rs

Make it possible to avoid rate limiting on docker.io

Add registry mirror configuration.

---

docs/companions.md

Minor mistake fixed for better sentence comprehension.

Bootstrapping companions section Update companions.md

---

docs/companions.md

Had grammatical mistakes. Needed slight paraphrasing for better understanding.

Service based section Update companions.md

---

api/src/tickets.rs

Some Jira instances don't work with validateQuery=False (e.g. the cloud instance) and thus PREvant needs to query the ticket information individually. Additionally, PREvant is a bit more relaxed with the response from Jira and ignores decoding errors because in some cases an HTTP client cannot distinguish between not found and not authenticated.

Improve Jira Response Handling

---

README.md

This section can be further improved and made more meaningful by adding information at the beginning that a detailed explanation can be found in a research paper and the link is provided in the 'Further Reading' section.

PREvant in the Nutshell section Update README.md

---

api/Cargo.lock
api/Cargo.toml
api/res/openapi.yml
api/src/apps/mod.rs
api/src/apps/routes/create_app_payload.rs
api/src/apps/routes/logs.rs
api/src/apps/routes/mod.rs
api/src/config/companion.rs
api/src/config/mod.rs
api/src/deployment/deployment_unit.rs
api/src/deployment/hooks.rs
api/src/infrastructure/kubernetes/deployment_unit.rs
api/src/infrastructure/kubernetes/infrastructure.rs
api/src/models/mod.rs
api/src/models/service_config/templating.rs
api/src/models/user_defined_parameters.rs
api/src/tickets.rs
docs/companions.md
docs/user-defined-schema.md

This PR brings user defined templating to companions in case of static configuration and bootstrapped from the infrastructure. This change provides the ability to implement more dynamic deployment scenarios.

Improve templating with user defined parameters

---

api/Cargo.lock
api/Cargo.toml
api/src/apps/host_meta_cache.rs
api/src/apps/mod.rs
api/src/apps/routes/mod.rs
api/src/infrastructure/docker.rs
api/src/infrastructure/dummy_infrastructure.rs
api/src/infrastructure/infrastructure.rs
api/src/infrastructure/kubernetes/deployment_unit.rs
api/src/infrastructure/kubernetes/infrastructure.rs
api/src/main.rs
api/src/models/mod.rs
api/src/models/service.rs
api/src/models/web_host_meta.rs
api/src/tickets.rs
api/src/webhooks.rs
frontend/src/store/index.js

This commit provides server side events (SSE) that push the updates of the applications to PREvant UI.

Automatic UI Updates

---

README.md
api/res/openapi.yml
api/src/models/service.rs
api/src/models/web_host_meta.rs
frontend/package-lock.json
frontend/package.json
frontend/src/AsyncApiUI.vue
frontend/src/ReviewAppCard.vue
frontend/src/main.js
frontend/src/store/index.js

If the service provides a link in the host-meta.json, that provides the
relation https://github.com/asyncapi/spec the URL will be rendered as
AsyncAPI documentation.

Integrate AsyncAPI

---

api-tests/Cargo.lock
api-tests/Cargo.toml
api/Cargo.lock
api/src/infrastructure/kubernetes/deployment_unit.rs

Make sure that any NetworkPolicy will be applied to the bootstrapped environment.

Copy NetworkPolicy during Kubernetes Bootstrapping

---

.github/workflows/integration-tests.yml
api-tests/tests/common/api_tests.rs
api-tests/tests/common/mod.rs
api-tests/tests/k3s.rs
api/src/apps/mod.rs
api/src/config/companion.rs
api/src/infrastructure/docker.rs
api/src/infrastructure/dummy_infrastructure.rs
api/src/infrastructure/infrastructure.rs
api/src/infrastructure/kubernetes/deployment_unit.rs
api/src/infrastructure/kubernetes/infrastructure.rs
api/src/infrastructure/kubernetes/payloads.rs
api/src/infrastructure/mod.rs
api/src/models/user_defined_parameters.rs
docs/Develop.md
docs/companions.md
examples/Kubernetes/Dockerfile.bootstrap
examples/Kubernetes/PREvant.yml

Duplicate User Defined Payload for Cloned Applications

---

.github/workflows/integration-tests.yml
README.md
api-tests/Cargo.lock
api-tests/Cargo.toml
api/Cargo.lock
api/Cargo.toml
api/src/apps/mod.rs
api/src/apps/routes/mod.rs
api/src/config/companion.rs
api/src/config/mod.rs
api/src/config/secret.rs
api/src/deployment/deployment_unit.rs
api/src/deployment/hooks.rs
api/src/infrastructure/docker.rs
api/src/infrastructure/kubernetes/deployment_unit.rs
api/src/infrastructure/kubernetes/infrastructure.rs
api/src/infrastructure/kubernetes/payloads.rs
api/src/infrastructure/traefik.rs
api/src/main.rs
api/src/models/app_status_change_id.rs
api/src/models/image.rs
api/src/models/service_config/mod.rs
api/src/models/web_hook_info.rs
api/src/registry.rs
api/src/tickets.rs
frontend/package-lock.json
frontend/package.json

This PR includes upgrades for the PREvant backend, frontend and
integration-tests. Also it provides Rust edition upgrade & cargo clippy
fixes.

Major Dependency Upgrades
